//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_01_519_Korshunova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int ID { get; set; }
        public Nullable<int> ID_event { get; set; }
        public string Activity_name { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<System.TimeSpan> Time_start { get; set; }
        public Nullable<int> ID_Moderator { get; set; }
        public Nullable<int> ID_Jury_1 { get; set; }
        public Nullable<int> ID_Jury_2 { get; set; }
        public Nullable<int> ID_Jury_3 { get; set; }
        public Nullable<int> ID_Jury_4 { get; set; }
        public Nullable<int> ID_Jury_5 { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Jury Jury { get; set; }
        public virtual Moderator Moderator { get; set; }
    }
}
