//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PM_01_519_Korshunova
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Moderator()
        {
            this.Activity = new HashSet<Activity>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_number { get; set; }
        public string FIO { get; set; }
        public string Gender { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> Birth_date { get; set; }
        public Nullable<int> ID_country { get; set; }
        public string Phone { get; set; }
        public string Direction { get; set; }
        public string Event { get; set; }
        public string Password { get; set; }
        public string Photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activity { get; set; }
        public virtual Country Country { get; set; }
    }
}
